In [1]:
import pandas as pd

# Demand for the energy transition for 2023

In [2]:
df_iea_demand_nze = pd.read_excel(r'data/data_metals.xlsx', sheet_name='EI_markets_etm')

In [3]:
df_iea_demand_nze = df_iea_demand_nze[df_iea_demand_nze['Scenario'] == 'NZE']

In [4]:
df_iea_demand_nze.columns = df_iea_demand_nze.columns.map(str)

In [5]:
df_iea_demand_nze = df_iea_demand_nze.rename(columns={'2022':'2023'})
#df_iea_demand_nze = df_iea_demand_nze.drop(columns=['2030', '2035', '2040', '2045', '2050'])

In [6]:
df_iea_demand_nze

,Metal,Technology,Market,Reference Product,Location,Scenario,2023,2030,2035,2040,2045,2050
1,Aluminium,Electricity Networks,"market for aluminium, wrought alloy (SM)","aluminium, wrought alloy",World,NZE,11045.666667,17872.000000,22818.000000,26403.000000,25148.000000,20759.00000
3,Arsenic,Solar PV,market for arsine,arsine,GLO,NZE,0.000000,0.551123,3.226120,15.291600,12.468600,15.81080
5,Boron,Wind,market for boric oxide,boric oxide,GLO,NZE,0.206005,0.705002,0.706441,0.625155,0.611907,0.86571
7,Cadmium,Solar PV,"market for cadmium, semiconductor-grade","cadmium, semiconductor-grade",GLO,NZE,0.670000,1.490000,1.420000,1.030000,0.650000,0.52000
9,Cadmium,Other low emissions power generation,"market for cadmium, semiconductor-grade","cadmium, semiconductor-grade",GLO,NZE,0.020000,0.030000,0.030000,0.030000,0.020000,0.02000
...,...,...,...,...,...,...,...,...,...,...,...,...
139,Zinc,Solar PV,market for zinc,zinc,GLO,NZE,10.452300,23.967800,25.097800,21.280500,17.351900,22.00310
141,Zinc,Wind,market for zinc,zinc,GLO,NZE,704.627000,1699.650000,1835.850000,1600.500000,1375.270000,1744.87000
143,Zinc,Other low emissions power generation,market for zinc,zinc,GLO,NZE,15.886700,46.892200,52.812200,48.449500,39.958100,33.86690
145,Zirconium,Other low emissions power generation,market for zirconium oxide,zirconium oxide,GLO,NZE,0.500000,1.030000,1.060000,0.800000,0.670000,0.58000
147,Zirconium,Hydrogen technologies,market for zirconium oxide,zirconium oxide,GLO,NZE,0.130000,10.110000,10.930000,9.300000,7.970000,10.27000

In [7]:
df_iea_demand_nze = df_iea_demand_nze.groupby('Metal', as_index=False)[['2023', '2030', '2035', '2040', '2045', '2050']].sum()

In [8]:
df_iea_demand_nze

,Metal,2023,2030,2035,2040,2045,2050
0,Aluminium,11045.666667,17872.000000,22818.000000,26403.000000,25148.000000,20759.000000
1,Arsenic,0.000000,0.551123,3.226120,15.291600,12.468600,15.810800
2,Boron,0.206005,0.705002,0.706441,0.625155,0.611907,0.865710
3,Cadmium,0.690000,1.520000,1.450000,1.060000,0.670000,0.540000
4,Chromium,212.030000,823.743000,752.042000,627.196000,506.176000,460.191000
5,Cobalt,64.390339,243.158376,253.041427,278.959988,313.205965,322.664329
6,Copper,6371.698723,15046.297135,18584.386227,19478.111466,19325.747932,19239.280520
7,Dysprosium,1.330000,4.890000,5.930000,5.710000,5.710000,6.370000
8,Gallium,0.015554,0.250526,1.316150,6.124140,4.988810,6.322200
9,Graphite (battery-grade),772.182600,5024.362000,6782.636000,6707.191000,5642.200000,4708.960000
10,Hafnium,0.007904,0.016231,0.016724,0.012513,0.010592,0.009137
11,Indium,0.100000,0.170000,0.190000,0.210000,0.160000,0.180000
12,Iridium,0.000199,0.007725,0.006817,0.004476,0.002690,0.001987
13,Lanthanum,0.003025,0.080592,0.063436,0.054333,0.046805,0.060699
14,Lead,12.510000,31.570000,26.260000,21.720000,18.980000,18.460000
15,Lithium,92.072260,615.591600,986.218800,1307.897000,1522.263000,1573.152000
16,Magnesium,8.055250,30.949800,54.578100,54.179800,42.314000,33.632400
17,Manganese,181.721910,861.266690,1522.497280,2119.476000,2555.030000,3051.414000
18,Molybdenum,28.869400,104.369000,92.045200,76.696100,63.135600,62.843700
19,Neodymium,12.598920,47.749800,57.865000,55.421400,55.423700,60.852600
20,Nickel,477.699146,2793.743800,3425.596200,3583.602800,3451.592700,3094.330800
21,Niobium,0.362905,1.974960,2.944910,2.867720,2.198950,1.701130
22,PGMs,0.000977,0.032054,0.060859,0.091245,0.098640,0.087478
23,Praseodymium,2.000000,7.900000,9.470000,9.110000,9.260000,10.690000
24,Selenium,0.132335,0.258088,0.233784,0.167636,0.091445,0.073190
25,Silicon,1126.101354,2029.791230,2255.964870,2105.155700,2050.800900,2479.973600
26,Silver,6.471640,11.670600,9.890380,6.271250,3.299750,1.703870
27,Tantalum,0.058661,0.437610,0.335397,0.266371,0.200396,0.146576
28,Tellurium,0.696188,1.550570,1.475590,1.072530,0.673667,0.535772
29,Terbium,0.390000,1.420000,1.660000,1.580000,1.590000,1.930000
30,Tin,2.150000,4.920000,5.140000,4.340000,3.540000,4.460000
31,Titanium,5.208690,22.692700,19.177500,15.070600,11.443700,9.475680
32,Tungsten,0.082334,0.169077,0.174207,0.130340,0.110329,0.095172
33,Vanadium,0.014047,35.268700,272.391000,556.407000,636.594000,773.134000
34,Yttrium,0.010000,0.030000,0.030000,0.010000,0.010000,0.010000
35,Zinc,730.966000,1770.510000,1913.760000,1670.230000,1432.580000,1800.740000
36,Zirconium,0.630000,11.140000,11.990000,10.100000,8.640000,10.850000

In [9]:
df_iea_demand_nze = pd.melt(
    df_iea_demand_nze, 
    id_vars=['Metal'], 
    var_name='Year', 
    value_name='Energy transition (kt)'
)

In [10]:
# We drop Hafnium as there is no production data, and rename graphite
df_iea_demand_nze['Metal'] = df_iea_demand_nze['Metal'].replace("Graphite (battery-grade)", "Graphite") 
df_iea_demand_nze.drop(df_iea_demand_nze[df_iea_demand_nze['Metal'] == 'Hafnium'].index, inplace=True)

In [11]:
df_iea_demand_nze

         Metal  Year  Energy transition (kt)
0    Aluminium  2023            11045.666667
1      Arsenic  2023                0.000000
2        Boron  2023                0.206005
3      Cadmium  2023                0.690000
4     Chromium  2023              212.030000
..         ...   ...                     ...
217   Tungsten  2050                0.095172
218   Vanadium  2050              773.134000
219    Yttrium  2050                0.010000
220       Zinc  2050             1800.740000
221  Zirconium  2050               10.850000

[216 rows x 3 columns]

In [12]:
df_iea_demand_nze_2023 = df_iea_demand_nze[df_iea_demand_nze['Year'] == '2023']

# Production data for 2023

In [13]:
df_production = pd.read_excel(r'data/data_minerals/data_availability_marin.xlsx', sheet_name='for_pandas')

In [14]:
col_to_keep = ['Metal', 'Total_refinery_production', 'Year', 'Unit']

In [15]:
df_production = df_production[col_to_keep]
df_production['Year'] = df_production['Year'].astype(str)
df_production

           Metal  Total_refinery_production  Year Unit
0      Aluminium               1.111111e+05  2023   kt
1        Arsenic               6.150000e+04  2023    t
2          Boron               3.055888e+03  2023   kt
3        Cadmium               2.410000e+04  2023    t
4       Chromium               1.570000e+04  2023   kt
5         Cobalt               2.000000e+05  2023    t
6         Copper               2.700000e+04  2023   kt
7     Dysprosium               1.376959e+03  2023    t
8        Gallium               6.330000e+05  2023   kg
9       Graphite               1.530000e+06  2023    t
10        Indium               1.020000e+03  2023    t
11       Iridium               1.954639e+03  2023   kg
12     Lanthanum               5.973131e+04  2023    t
13          Lead               1.144430e+07  2023    t
14       Lithium               1.489401e+05  2023    t
15     Magnesium               9.000000e+02  2023   kt
16     Manganese               1.372000e+04  2023   kt
17    Molybdenum               1.488000e+05  2023    t
18     Neodymium               3.781688e+04  2023    t
19        Nickel               3.552004e+06  2023    t
20       Niobium               7.810000e+04  2023    t
21          PGMs               1.172491e+05  2023   kg
22  Praseodymium               1.152496e+04  2023    t
23      Selenium               3.530000e+03  2023    t
24       Silicon               4.280000e+03  2023   kt
25        Silver               2.146520e+04  2023    t
26      Tantalum               1.321281e+03  2023    t
27     Tellurium               9.440000e+02  2023    t
28       Terbium               3.759461e+02  2023    t
29           Tin               2.691176e+05  2023    t
30      Titanium               3.200000e+05  2023    t
31      Tungsten               7.041429e+04  2023    t
32      Vanadium               3.418611e+04  2023    t
33       Yttrium               7.909375e+03  2023    t
34          Zinc               1.350360e+04  2023   kt
35     Zirconium               1.231200e+03  2023   kt

In [16]:
def convert_to_kt(row):
    if row['Unit'] == 't':
        return row['Total_refinery_production'] / 1000
    elif row['Unit'] == 'kg':
        return row['Total_refinery_production'] / 1000000
    else:  # already in kt
        return row['Total_refinery_production']

In [17]:
df_production['Total_refinery_production'] = df_production.apply(convert_to_kt, axis=1)
df_production.rename(columns={'Total_refinery_production': 'Total refinery production (kt)'}, inplace=True)
df_production.drop(columns=['Unit'], inplace=True)

In [18]:
df_production

           Metal  Total refinery production (kt)  Year
0      Aluminium                   111111.111111  2023
1        Arsenic                       61.500000  2023
2          Boron                     3055.888000  2023
3        Cadmium                       24.100000  2023
4       Chromium                    15700.000000  2023
5         Cobalt                      200.000000  2023
6         Copper                    27000.000000  2023
7     Dysprosium                        1.376959  2023
8        Gallium                        0.633000  2023
9       Graphite                     1530.000000  2023
10        Indium                        1.020000  2023
11       Iridium                        0.001955  2023
12     Lanthanum                       59.731313  2023
13          Lead                    11444.304933  2023
14       Lithium                      148.940054  2023
15     Magnesium                      900.000000  2023
16     Manganese                    13720.000000  2023
17    Molybdenum                      148.800000  2023
18     Neodymium                       37.816884  2023
19        Nickel                     3552.003552  2023
20       Niobium                       78.100000  2023
21          PGMs                        0.117249  2023
22  Praseodymium                       11.524961  2023
23      Selenium                        3.530000  2023
24       Silicon                     4280.000000  2023
25        Silver                       21.465201  2023
26      Tantalum                        1.321281  2023
27     Tellurium                        0.944000  2023
28       Terbium                        0.375946  2023
29           Tin                      269.117647  2023
30      Titanium                      320.000000  2023
31      Tungsten                       70.414286  2023
32      Vanadium                       34.186113  2023
33       Yttrium                        7.909375  2023
34          Zinc                    13503.600000  2023
35     Zirconium                     1231.200000  2023

# Compute demand for the rest of the economy

In [19]:
df = df_production.merge(df_iea_demand_nze_2023, on=['Metal', 'Year'], how='left')

In [20]:
df

           Metal  Total refinery production (kt)  Year  Energy transition (kt)
0      Aluminium                   111111.111111  2023            11045.666667
1        Arsenic                       61.500000  2023                0.000000
2          Boron                     3055.888000  2023                0.206005
3        Cadmium                       24.100000  2023                0.690000
4       Chromium                    15700.000000  2023              212.030000
5         Cobalt                      200.000000  2023               64.390339
6         Copper                    27000.000000  2023             6371.698723
7     Dysprosium                        1.376959  2023                1.330000
8        Gallium                        0.633000  2023                0.015554
9       Graphite                     1530.000000  2023              772.182600
10        Indium                        1.020000  2023                0.100000
11       Iridium                        0.001955  2023                0.000199
12     Lanthanum                       59.731313  2023                0.003025
13          Lead                    11444.304933  2023               12.510000
14       Lithium                      148.940054  2023               92.072260
15     Magnesium                      900.000000  2023                8.055250
16     Manganese                    13720.000000  2023              181.721910
17    Molybdenum                      148.800000  2023               28.869400
18     Neodymium                       37.816884  2023               12.598920
19        Nickel                     3552.003552  2023              477.699146
20       Niobium                       78.100000  2023                0.362905
21          PGMs                        0.117249  2023                0.000977
22  Praseodymium                       11.524961  2023                2.000000
23      Selenium                        3.530000  2023                0.132335
24       Silicon                     4280.000000  2023             1126.101354
25        Silver                       21.465201  2023                6.471640
26      Tantalum                        1.321281  2023                0.058661
27     Tellurium                        0.944000  2023                0.696188
28       Terbium                        0.375946  2023                0.390000
29           Tin                      269.117647  2023                2.150000
30      Titanium                      320.000000  2023                5.208690
31      Tungsten                       70.414286  2023                0.082334
32      Vanadium                       34.186113  2023                0.014047
33       Yttrium                        7.909375  2023                0.010000
34          Zinc                    13503.600000  2023              730.966000
35     Zirconium                     1231.200000  2023                0.630000

In [21]:
df['Rest of the economy (kt)'] = df['Total refinery production (kt)'] - df['Energy transition (kt)']

In [22]:
# Let's remove Terbium for now to avoid negative values
df = df[df['Metal'] != 'Terbium']

In [23]:
# Move 'Year' to the end
cols = [col for col in df.columns if col != 'Year'] + ['Year']
df = df[cols]

In [24]:
df.drop(columns=['Total refinery production (kt)'], inplace=True)

In [25]:
df

           Metal  Energy transition (kt)  Rest of the economy (kt)  Year
0      Aluminium            11045.666667             100065.444444  2023
1        Arsenic                0.000000                 61.500000  2023
2          Boron                0.206005               3055.681995  2023
3        Cadmium                0.690000                 23.410000  2023
4       Chromium              212.030000              15487.970000  2023
5         Cobalt               64.390339                135.609661  2023
6         Copper             6371.698723              20628.301277  2023
7     Dysprosium                1.330000                  0.046959  2023
8        Gallium                0.015554                  0.617446  2023
9       Graphite              772.182600                757.817400  2023
10        Indium                0.100000                  0.920000  2023
11       Iridium                0.000199                  0.001756  2023
12     Lanthanum                0.003025                 59.728289  2023
13          Lead               12.510000              11431.794933  2023
14       Lithium               92.072260                 56.867794  2023
15     Magnesium                8.055250                891.944750  2023
16     Manganese              181.721910              13538.278090  2023
17    Molybdenum               28.869400                119.930600  2023
18     Neodymium               12.598920                 25.217964  2023
19        Nickel              477.699146               3074.304406  2023
20       Niobium                0.362905                 77.737095  2023
21          PGMs                0.000977                  0.116272  2023
22  Praseodymium                2.000000                  9.524961  2023
23      Selenium                0.132335                  3.397665  2023
24       Silicon             1126.101354               3153.898646  2023
25        Silver                6.471640                 14.993561  2023
26      Tantalum                0.058661                  1.262620  2023
27     Tellurium                0.696188                  0.247812  2023
29           Tin                2.150000                266.967647  2023
30      Titanium                5.208690                314.791310  2023
31      Tungsten                0.082334                 70.331952  2023
32      Vanadium                0.014047                 34.172066  2023
33       Yttrium                0.010000                  7.899375  2023
34          Zinc              730.966000              12772.634000  2023
35     Zirconium                0.630000               1230.570000  2023

# Project production to 2050

In [26]:
def project_demand(df_base, df_iea, iam_df, parameter='gdp', scenario='SSP2'):
    """
    Project annual demand for energy transition and rest of the economy from base year (2023)
    to target years using IAM trends (GDP or population) for a given scenario.

    Args:
        df_base (pd.DataFrame): Base DataFrame with columns 
            ['Metal', 'Energy transition (kt)', 'Rest of the economy (kt)', 'Year'].
            Must include Year=2023 values.
        df_iea (pd.DataFrame): IEA demand DataFrame with ['Metal', 'Year', 'Energy transition (kt)']
            for years (e.g., 2023, 2030, …, 2050).
        iam_df (pd.DataFrame): IAM projections DataFrame with columns
            ['model','scenario','region','variable','unit', <year columns as strings>].
        parameter (str): 'gdp' or 'population' to choose trend variable.
        scenario (str): IAM scenario name, e.g., 'SSP2'.

    Returns:
        pd.DataFrame: Long-format DataFrame with columns
        ['Metal', 'Year', 'Energy transition (kt)', 'Rest of the economy (kt)'] for each Metal-Year.
    """
    # 1) Map parameter to IAM variable
    var_map = {'gdp': 'GDP|PPP', 'population': 'Population'}
    param_label = var_map.get(parameter.lower())
    if param_label is None:
        raise ValueError("parameter must be 'gdp' or 'population'")

    # 2) Filter IAM data
    iam_sub = iam_df[
        (iam_df['scenario'] == scenario) &
        (iam_df['region'] == 'World') &
        (iam_df['variable'] == param_label)
    ]
    if iam_sub.empty:
        raise ValueError(f"No IAM data for scenario={scenario}, variable={param_label}")

    # 3) Identify year columns (strings like '2025', etc.)
    year_cols = [c for c in iam_sub.columns if c.isdigit()]

    # 4) Melt to long form
    iam_long = iam_sub.melt(
        id_vars=['model','scenario','region','variable','unit'],
        value_vars=year_cols,
        var_name='Year',
        value_name='Value'
    )
    iam_long['Year'] = iam_long['Year'].astype(int)

    # 5) — NEW: aggregate across models so each Year is unique
    iam_yearly = (
        iam_long
        .groupby('Year', as_index=True)['Value']
        .mean()
        .sort_index()
    )

    # 6) Determine target years from IEA data
    df_iea = df_iea.copy()
    df_iea['Year'] = pd.to_numeric(df_iea['Year'], errors='coerce').astype(int)
    years = sorted(df_iea['Year'].dropna().unique())

    # 7) Interpolate IAM trend to include all target years + base year 2023
    interp_index = sorted(set(iam_yearly.index) | set(years) | {2023})
    iam_interp = iam_yearly.reindex(interp_index).interpolate(method='linear')

    # 8) Compute relative growth factors (base 2023 = 1.0)
    base_val = iam_interp.loc[2023]
    factors = {yr: iam_interp.loc[yr] / base_val for yr in years}

    # 9) Extract base rest-of-economy values for 2023
    df_base = df_base.copy()
    df_base['Year'] = pd.to_numeric(df_base['Year'], errors='coerce').astype(int)
    base_rest = df_base[df_base['Year'] == 2023].set_index('Metal')['Rest of the economy (kt)']

    # 10) Build the projected records
    records = []
    for metal, rest_2023 in base_rest.items():
        for yr in years:
            # IEA energy-transition demand
            et_vals = df_iea[
                (df_iea['Metal'] == metal) & (df_iea['Year'] == yr)
            ]['Energy transition (kt)']
            et_value = et_vals.iloc[0] if not et_vals.empty else pd.NA

            # Project rest-of-economy demand
            rest_proj = rest_2023 * factors[yr]

            records.append({
                'Metal': metal,
                'Year': yr,
                'Energy transition (kt)': et_value,
                'Rest of the economy (kt)': rest_proj
            })

    return pd.DataFrame.from_records(records)

In [27]:
df_ssp = pd.read_csv(r'data/data_ssp/iamdf_ssp.csv')

In [28]:
df_ssp

,model,scenario,region,variable,unit,1950,1955,1960,1965,1970,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
0,IIASA GDP 2023,SSP2,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,255138.335123,277925.973504,303738.457766,329904.061454,355181.883172,379416.234223,403091.576433,426844.242781,451003.054434,4.736919e+05
1,IIASA GDP 2023,SSP3,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,225693.405454,237807.806366,251465.089082,263876.784353,274109.176024,282837.904227,291093.415351,299532.073994,308528.092060,3.176999e+05
2,IIASA GDP 2023,SSP4,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,242718.489915,262626.219514,286025.130813,309511.569348,331753.809478,353275.893133,375617.507533,399219.452589,424297.929059,4.497758e+05
3,IIASA GDP 2023,SSP5,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,303063.278481,339134.662984,381314.518550,422795.651999,460310.806649,492471.244082,519576.501571,542624.652729,564477.011532,5.835374e+05
4,IIASA-WiC POP 2023,Historical Reference,World,Population,million,2476.354507,2717.192825,2993.980903,3300.599684,3655.64095,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,IIASA-WiC POP 2023,SSP1,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,9202.151029,9213.262946,9178.893434,9106.377915,8999.413476,8858.470328,8682.371633,8474.137111,8238.814653,7.979164e+03
6,IIASA-WiC POP 2023,SSP2,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,9773.968144,9915.120022,10018.007006,10087.997781,10125.479114,10129.680830,10103.453315,10052.324966,9979.043839,9.884518e+03
7,IIASA-WiC POP 2023,SSP3,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,10434.441507,10770.760005,11094.131841,11406.313579,11703.830762,11987.472742,12262.506162,12533.952723,12800.281382,1.305898e+04
8,IIASA-WiC POP 2023,SSP4,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,10233.976397,10513.499547,10768.949236,11001.646474,11210.018164,11395.574578,11563.790683,11720.583524,11865.380260,1.199471e+04
9,IIASA-WiC POP 2023,SSP5,World,Population,million,NaN,NaN,NaN,NaN,NaN,...,9201.376985,9213.460664,9180.525398,9110.103583,9006.029578,8868.761464,8696.932656,8493.238260,8262.352940,8.006621e+03
10,OECD ENV-Growth 2023,Historical Reference,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,OECD ENV-Growth 2023,SSP1,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,342519.622140,379875.668420,418481.884650,456578.197690,493592.064640,529005.618020,562481.066850,593986.279530,623451.253340,6.504840e+05
12,OECD ENV-Growth 2023,SSP2,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,311753.182600,343908.603280,378120.862750,413225.062780,449104.420620,485594.601470,522887.292160,561317.292620,600977.663520,6.416547e+05
13,OECD ENV-Growth 2023,SSP3,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,258392.181650,271794.227522,284623.679793,296334.880140,307271.673330,317678.260000,327919.571200,338267.024440,348766.663470,3.593982e+05
14,OECD ENV-Growth 2023,SSP4,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,303488.802611,329395.882470,355920.720090,382261.602350,408559.430700,434932.974930,461740.283460,489472.059910,518486.839400,5.489459e+05
15,OECD ENV-Growth 2023,SSP5,World,GDP|PPP,billion USD_2017/yr,NaN,NaN,NaN,NaN,NaN,...,409164.586980,469503.373190,535195.614480,604238.057190,675916.326720,749501.136010,824441.939340,900572.336930,977617.488740,1.054733e+06

In [40]:
proj_df = project_demand(
    df_base=df, 
    df_iea=df_iea_demand_nze, 
    iam_df=df_ssp, 
    parameter='gdp', 
    scenario='SSP2'
)

In [41]:
proj_df

         Metal  Year  Energy transition (kt)  Rest of the economy (kt)
0    Aluminium  2023            11045.666667             100065.444444
1    Aluminium  2030            17872.000000             121513.491726
2    Aluminium  2035            22818.000000             137047.299547
3    Aluminium  2040            26403.000000             153044.408523
4    Aluminium  2045            25148.000000             170972.866070
..         ...   ...                     ...                       ...
205  Zirconium  2030               11.140000               1494.330619
206  Zirconium  2035               11.990000               1685.359980
207  Zirconium  2040               10.100000               1882.086857
208  Zirconium  2045                8.640000               2102.564786
209  Zirconium  2050               10.850000               2336.175863

[210 rows x 4 columns]

In [42]:
proj_df.to_csv(r'results/energy_transition_vs_roe.csv', index=False)

# Create a df for lca calculation for the rest of the economy

In [43]:
proj_df

         Metal  Year  Energy transition (kt)  Rest of the economy (kt)
0    Aluminium  2023            11045.666667             100065.444444
1    Aluminium  2030            17872.000000             121513.491726
2    Aluminium  2035            22818.000000             137047.299547
3    Aluminium  2040            26403.000000             153044.408523
4    Aluminium  2045            25148.000000             170972.866070
..         ...   ...                     ...                       ...
205  Zirconium  2030               11.140000               1494.330619
206  Zirconium  2035               11.990000               1685.359980
207  Zirconium  2040               10.100000               1882.086857
208  Zirconium  2045                8.640000               2102.564786
209  Zirconium  2050               10.850000               2336.175863

[210 rows x 4 columns]

In [44]:
def transform_transition_data(df, value_col='Rest of the economy (kt)'):
    """
    Transforms a long-format DataFrame into wide format with one row per metal
    and each year as a separate column. Adds placeholder metadata columns.

    Parameters
    ----------
    df : pd.DataFrame
        Must contain ['Metal', 'Year', value_col] and optionally 'Energy transition (kt)'
    value_col : str
        Column to pivot (default: 'Rest of the economy (kt)')

    Returns
    -------
    pd.DataFrame
        Wide-format DataFrame with metadata columns and selected year columns.
    """
    # Remove the energy transition column if it exists
    df_cleaned = df.drop(columns=[col for col in df.columns if 'Energy transition' in col], errors='ignore')

    # Pivot to wide format
    df_pivoted = df_cleaned.pivot(index='Metal', columns='Year', values=value_col).reset_index()

    # Remove column name from multi-index (gets rid of 'Year' above the year columns)
    df_pivoted.columns.name = None

    # Insert empty metadata columns
    for col in ['Technology', 'Market', 'Reference Product', 'Location', 'Scenario'][::-1]:
        df_pivoted.insert(1, col, '')

    # Desired order — only include years that exist in the data
    desired_order = ['Metal', 'Technology', 'Market', 'Reference Product', 'Location', 'Scenario',
                     2023, 2030, 2035, 2040, 2045, 2050]
    final_order = [col for col in desired_order if col in df_pivoted.columns]

    return df_pivoted[final_order]

In [45]:
df_roe_for_lca = transform_transition_data(proj_df, value_col='Rest of the economy (kt)')

In [46]:
df_roe_for_lca

,Metal,Technology,Market,Reference Product,Location,Scenario,2023,2030,2035,2040,2045,2050
0,Aluminium,,,,,,100065.444444,121513.491726,137047.299547,153044.408523,170972.866070,189969.263061
1,Arsenic,,,,,,61.500000,74.681922,84.228966,94.060754,105.079544,116.754687
2,Boron,,,,,,3055.681995,3710.637482,4184.990813,4673.491895,5220.970250,5801.060096
3,Cadmium,,,,,,23.410000,28.427704,32.061790,35.804264,39.998571,44.442719
4,Chromium,,,,,,15487.970000,18807.664573,21211.962589,23687.969619,26462.907702,29403.139751
5,Cobalt,,,,,,135.609661,164.676263,185.727830,207.407268,231.704087,257.448189
6,Copper,,,,,,20628.301277,25049.775479,28252.040452,31549.814077,35245.731542,39161.802694
7,Dysprosium,,,,,,0.046959,0.057024,0.064314,0.071821,0.080235,0.089149
8,Gallium,,,,,,0.617446,0.749790,0.845640,0.944349,1.054975,1.172191
9,Graphite,,,,,,757.817400,920.248132,1037.889041,1159.038631,1294.814744,1438.678595
10,Indium,,,,,,0.920000,1.117193,1.260011,1.407088,1.571922,1.746574
11,Iridium,,,,,,0.001756,0.002132,0.002405,0.002685,0.003000,0.003333
12,Lanthanum,,,,,,59.728289,72.530462,81.802471,91.351022,102.052379,113.391181
13,Lead,,,,,,11431.794933,13882.088134,15656.719792,17484.280448,19532.484514,21702.693381
14,Lithium,,,,,,56.867794,69.056849,77.884805,86.976059,97.164909,107.960676
15,Magnesium,,,,,,891.944750,1083.124365,1221.586733,1364.178788,1523.986139,1693.312689
16,Manganese,,,,,,13538.278090,16440.075311,18541.710008,20706.026683,23131.643691,25701.746753
17,Molybdenum,,,,,,119.930600,145.636549,164.254153,183.427035,204.914679,227.682272
18,Neodymium,,,,,,25.217964,30.623188,34.537936,38.569443,43.087678,47.875049
19,Nickel,,,,,,3074.304406,3733.251424,4210.495633,4701.973814,5252.788696,5836.413816
20,Niobium,,,,,,77.737095,94.399279,106.466913,118.894467,132.822414,147.580004
21,PGMs,,,,,,0.116272,0.141193,0.159243,0.177831,0.198663,0.220736
22,Praseodymium,,,,,,9.524961,11.566543,13.045164,14.567886,16.274448,18.082664
23,Selenium,,,,,,3.397665,4.125921,4.653363,5.196535,5.805286,6.450298
24,Silicon,,,,,,3153.898646,3829.905910,4319.506048,4823.708679,5388.784248,5987.519517
25,Silver,,,,,,14.993561,18.207284,20.534832,22.931799,25.618156,28.464529
26,Tantalum,,,,,,1.262620,1.533251,1.729256,1.931106,2.157327,2.397022
27,Tellurium,,,,,,0.247812,0.300928,0.339398,0.379014,0.423414,0.470459
28,Tin,,,,,,266.967647,324.189546,365.632665,408.311839,456.143717,506.824783
29,Titanium,,,,,,314.791310,382.263742,431.130838,481.455413,537.855728,597.615626
30,Tungsten,,,,,,70.331952,85.406917,96.325002,107.568722,120.169910,133.521709
31,Vanadium,,,,,,34.172066,41.496513,46.801265,52.264232,58.386750,64.873965
32,Yttrium,,,,,,7.899375,9.592529,10.818800,12.081646,13.496956,14.996571
33,Zinc,,,,,,12772.634000,15510.322914,17493.101715,19535.017574,21823.456183,24248.209577
34,Zirconium,,,,,,1230.570000,1494.330619,1685.359980,1882.086857,2102.564786,2336.175863

In [47]:
df_roe_for_lca.to_csv(r'results/roe_for_lca.csv', index=False)